FROM python:3.11-slim

WORKDIR /app

COPY requirements_flask.txt .

RUN pip install --no-cache-dir -r requirements_flask.txt

COPY resume.py /app/
COPY templates /app/templates

ENV FLASK_APP=resume.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

CMD ["flask", "run"]

